-- ============================================================================
-- Script: 02_create_tables.sql
-- Project: MelodyMart Web-Based Music Store
-- DBMS: Microsoft SQL Server
-- Description: Creates all 21 relational tables, primary keys, foreign keys,
--              UNIQUE constraints, NOT NULL constraints, and CHECK constraints.
-- 

USE MelodyMartDB;
GO


-- DROP EXISTING TABLES (Reverse Dependency Order)

IF OBJECT_ID('dbo.DOWNLOAD', 'U') IS NOT NULL DROP TABLE dbo.DOWNLOAD;
IF OBJECT_ID('dbo.LIBRARY_ITEMS', 'U') IS NOT NULL DROP TABLE dbo.LIBRARY_ITEMS;
IF OBJECT_ID('dbo.DIGITAL_LIBRARY', 'U') IS NOT NULL DROP TABLE dbo.DIGITAL_LIBRARY;
IF OBJECT_ID('dbo.REVIEW', 'U') IS NOT NULL DROP TABLE dbo.REVIEW;
IF OBJECT_ID('dbo.COMPLAINT', 'U') IS NOT NULL DROP TABLE dbo.COMPLAINT;
IF OBJECT_ID('dbo.FAQ', 'U') IS NOT NULL DROP TABLE dbo.FAQ;
IF OBJECT_ID('dbo.ALBUM_PROMOTION', 'U') IS NOT NULL DROP TABLE dbo.ALBUM_PROMOTION;
IF OBJECT_ID('dbo.PROMOTION', 'U') IS NOT NULL DROP TABLE dbo.PROMOTION;
IF OBJECT_ID('dbo.PAYMENT', 'U') IS NOT NULL DROP TABLE dbo.PAYMENT;
IF OBJECT_ID('dbo.ORDER_ITEM', 'U') IS NOT NULL DROP TABLE dbo.ORDER_ITEM;
IF OBJECT_ID('dbo.ORDERS', 'U') IS NOT NULL DROP TABLE dbo.ORDERS;
IF OBJECT_ID('dbo.CART_ITEM', 'U') IS NOT NULL DROP TABLE dbo.CART_ITEM;
IF OBJECT_ID('dbo.CART', 'U') IS NOT NULL DROP TABLE dbo.CART;
IF OBJECT_ID('dbo.TRACK', 'U') IS NOT NULL DROP TABLE dbo.TRACK;
IF OBJECT_ID('dbo.ALBUM', 'U') IS NOT NULL DROP TABLE dbo.ALBUM;
IF OBJECT_ID('dbo.Catalog', 'U') IS NOT NULL DROP TABLE dbo.Catalog;
IF OBJECT_ID('dbo.GENRE', 'U') IS NOT NULL DROP TABLE dbo.GENRE;
IF OBJECT_ID('dbo.ARTIST', 'U') IS NOT NULL DROP TABLE dbo.ARTIST;
IF OBJECT_ID('dbo.LISTENER', 'U') IS NOT NULL DROP TABLE dbo.LISTENER;
IF OBJECT_ID('dbo.ADMINISTRATOR', 'U') IS NOT NULL DROP TABLE dbo.ADMINISTRATOR;
IF OBJECT_ID('dbo.USER', 'U') IS NOT NULL DROP TABLE dbo.[USER];
GO

-- 1. USER & AUTHENTICATION MODULE (Class-Table Inheritance)

-- 1.1 USER (Superclass Table)
CREATE TABLE dbo.[USER] (
    UserID INT IDENTITY(1,1) NOT NULL,
    FirstName NVARCHAR(50) NOT NULL,
    LastName NVARCHAR(50) NOT NULL,
    Email NVARCHAR(100) NOT NULL,
    PasswordHash NVARCHAR(255) NOT NULL,
    PhoneNumber NVARCHAR(20) NULL,
    RegistrationDate DATETIME2 NOT NULL DEFAULT GETDATE(),
    AccountStatus NVARCHAR(20) NOT NULL DEFAULT 'Active',
    CONSTRAINT PK_USER PRIMARY KEY CLUSTERED (UserID),
    CONSTRAINT UQ_USER_Email UNIQUE (Email),
    CONSTRAINT CK_USER_AccountStatus CHECK (AccountStatus IN ('Active', 'Inactive', 'Suspended'))
);
GO

-- 1.2 ADMINISTRATOR (Subclass Table)
CREATE TABLE dbo.[ADMINISTRATOR] (
    AdminID INT NOT NULL,
    AdminRole NVARCHAR(50) NOT NULL DEFAULT 'Admin',
    CONSTRAINT PK_ADMINISTRATOR PRIMARY KEY CLUSTERED (AdminID),
    CONSTRAINT FK_ADMINISTRATOR_USER FOREIGN KEY (AdminID)
        REFERENCES dbo.[USER] (UserID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT CK_ADMINISTRATOR_Role CHECK (AdminRole IN ('SuperAdmin', 'StoreManager', 'SalesManager', 'CustomerSupport', 'CatalogCoordinator'))
);
GO

-- 1.3 LISTENER (Subclass Table)
CREATE TABLE dbo.[LISTENER] (
    ListenerID INT NOT NULL,
    CONSTRAINT PK_LISTENER PRIMARY KEY CLUSTERED (ListenerID),
    CONSTRAINT FK_LISTENER_USER FOREIGN KEY (ListenerID)
        REFERENCES dbo.[USER] (UserID)
        ON DELETE CASCADE ON UPDATE CASCADE
);
GO

-- 2. ARTIST, GENRE & MUSIC CATALOG MODULE

-- 2.1 ARTIST
CREATE TABLE dbo.[ARTIST] (
    ArtistID INT IDENTITY(1,1) NOT NULL,
    ArtistName NVARCHAR(100) NOT NULL,
    Biography NVARCHAR(MAX) NULL,
    Country NVARCHAR(50) NULL,
    CONSTRAINT PK_ARTIST PRIMARY KEY CLUSTERED (ArtistID)
);
GO

-- 2.2 GENRE
CREATE TABLE dbo.[GENRE] (
    GenreID INT IDENTITY(1,1) NOT NULL,
    GenreName NVARCHAR(50) NOT NULL,
    Description NVARCHAR(255) NULL,
    CONSTRAINT PK_GENRE PRIMARY KEY CLUSTERED (GenreID),
    CONSTRAINT UQ_GENRE_GenreName UNIQUE (GenreName)
);
GO

-- 2.3 Catalog
CREATE TABLE dbo.[Catalog] (
    CatalogID INT IDENTITY(1,1) NOT NULL,
    CatalogName NVARCHAR(100) NOT NULL,
    Description NVARCHAR(MAX) NULL,
    Price DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    CreatedDate DATETIME2 NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_Catalog PRIMARY KEY CLUSTERED (CatalogID),
    CONSTRAINT CK_Catalog_Price CHECK (Price >= 0)
);
GO

-- 2.4 ALBUM
CREATE TABLE dbo.[ALBUM] (
    AlbumID INT IDENTITY(1,1) NOT NULL,
    AlbumTitle NVARCHAR(150) NOT NULL,
    ReleaseDate DATE NULL,
    AlbumStatus NVARCHAR(20) NOT NULL DEFAULT 'Available',
    Price DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    Description NVARCHAR(MAX) NULL,
    CoverImageURL NVARCHAR(255) NULL,
    ArtistID INT NOT NULL,
    GenreID INT NOT NULL,
    CatalogID INT NULL,
    CONSTRAINT PK_ALBUM PRIMARY KEY CLUSTERED (AlbumID),
    CONSTRAINT FK_ALBUM_ARTIST FOREIGN KEY (ArtistID)
        REFERENCES dbo.[ARTIST] (ArtistID)
        ON DELETE NO ACTION ON UPDATE CASCADE,
    CONSTRAINT FK_ALBUM_GENRE FOREIGN KEY (GenreID)
        REFERENCES dbo.[GENRE] (GenreID)
        ON DELETE NO ACTION ON UPDATE CASCADE,
    CONSTRAINT FK_ALBUM_Catalog FOREIGN KEY (CatalogID)
        REFERENCES dbo.[Catalog] (CatalogID)
        ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT CK_ALBUM_Price CHECK (Price >= 0),
    CONSTRAINT CK_ALBUM_AlbumStatus CHECK (AlbumStatus IN ('Available', 'Unavailable', 'ComingSoon', 'Discontinued'))
);
GO

-- 2.5 TRACK (Weak Entity)
CREATE TABLE dbo.[TRACK] (
    TrackID INT IDENTITY(1,1) NOT NULL,
    AlbumID INT NOT NULL,
    TrackTitle NVARCHAR(150) NOT NULL,
    TrackNumber INT NOT NULL,
    Duration INT NOT NULL,
    AudioFileURL NVARCHAR(255) NOT NULL,
    CONSTRAINT PK_TRACK PRIMARY KEY CLUSTERED (TrackID),
    CONSTRAINT FK_TRACK_ALBUM FOREIGN KEY (AlbumID)
        REFERENCES dbo.[ALBUM] (AlbumID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT UQ_TRACK_AlbumTrackNumber UNIQUE (AlbumID, TrackNumber),
    CONSTRAINT CK_TRACK_Duration CHECK (Duration > 0),
    CONSTRAINT CK_TRACK_TrackNumber CHECK (TrackNumber > 0)
);
GO


-- 3. SHOPPING CART & ORDER / SALES MANAGEMENT MODULE


-- 3.1 CART
CREATE TABLE dbo.[CART] (
    CartID INT IDENTITY(1,1) NOT NULL,
    ListenerID INT NOT NULL,
    CreatedDate DATETIME2 NOT NULL DEFAULT GETDATE(),
    LastUpdatedDate DATETIME2 NOT NULL DEFAULT GETDATE(),
    CartStatus NVARCHAR(20) NOT NULL DEFAULT 'Active',
    CONSTRAINT PK_CART PRIMARY KEY CLUSTERED (CartID),
    CONSTRAINT UQ_CART_ListenerID UNIQUE (ListenerID),
    CONSTRAINT FK_CART_LISTENER FOREIGN KEY (ListenerID)
        REFERENCES dbo.[LISTENER] (ListenerID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT CK_CART_CartStatus CHECK (CartStatus IN ('Active', 'Abandoned', 'Converted'))
);
GO

-- 3.2 CART_ITEM (Weak Entity)
CREATE TABLE dbo.[CART_ITEM] (
    CartID INT NOT NULL,
    ItemNo INT NOT NULL,
    AlbumID INT NULL,
    CatalogID INT NULL,
    Quantity INT NOT NULL DEFAULT 1,
    UnitPrice DECIMAL(10,2) NOT NULL,
    AddedDate DATETIME2 NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_CART_ITEM PRIMARY KEY CLUSTERED (CartID, ItemNo),
    CONSTRAINT FK_CART_ITEM_CART FOREIGN KEY (CartID)
        REFERENCES dbo.[CART] (CartID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_CART_ITEM_ALBUM FOREIGN KEY (AlbumID)
        REFERENCES dbo.[ALBUM] (AlbumID)
        ON DELETE NO ACTION ON UPDATE CASCADE,
    CONSTRAINT FK_CART_ITEM_Catalog FOREIGN KEY (CatalogID)
        REFERENCES dbo.[Catalog] (CatalogID)
        ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT CK_CART_ITEM_Quantity CHECK (Quantity > 0),
    CONSTRAINT CK_CART_ITEM_UnitPrice CHECK (UnitPrice >= 0),
    CONSTRAINT CK_CART_ITEM_ItemRef CHECK (
        (AlbumID IS NOT NULL AND CatalogID IS NULL) OR
        (AlbumID IS NULL AND CatalogID IS NOT NULL)
    )
);
GO

-- 3.3 ORDERS
CREATE TABLE dbo.[ORDERS] (
    OrderID INT IDENTITY(1,1) NOT NULL,
    ListenerID INT NOT NULL,
    OrderDate DATETIME2 NOT NULL DEFAULT GETDATE(),
    OrderStatus NVARCHAR(20) NOT NULL DEFAULT 'Pending',
    TotalAmount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    CONSTRAINT PK_ORDERS PRIMARY KEY CLUSTERED (OrderID),
    CONSTRAINT FK_ORDERS_LISTENER FOREIGN KEY (ListenerID)
        REFERENCES dbo.[LISTENER] (ListenerID)
        ON DELETE NO ACTION ON UPDATE CASCADE,
    CONSTRAINT CK_ORDERS_TotalAmount CHECK (TotalAmount >= 0),
    CONSTRAINT CK_ORDERS_OrderStatus CHECK (OrderStatus IN ('Pending', 'Processing', 'Completed', 'Cancelled', 'Refunded'))
);
GO

-- 3.4 ORDER_ITEM (Weak Entity)
CREATE TABLE dbo.[ORDER_ITEM] (
    OrderID INT NOT NULL,
    ItemNo INT NOT NULL,
    AlbumID INT NULL,
    CatalogID INT NULL,
    Quantity INT NOT NULL DEFAULT 1,
    UnitPrice DECIMAL(10,2) NOT NULL,
    CONSTRAINT PK_ORDER_ITEM PRIMARY KEY CLUSTERED (OrderID, ItemNo),
    CONSTRAINT FK_ORDER_ITEM_ORDERS FOREIGN KEY (OrderID)
        REFERENCES dbo.[ORDERS] (OrderID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_ORDER_ITEM_ALBUM FOREIGN KEY (AlbumID)
        REFERENCES dbo.[ALBUM] (AlbumID)
        ON DELETE NO ACTION ON UPDATE CASCADE,
    CONSTRAINT FK_ORDER_ITEM_Catalog FOREIGN KEY (CatalogID)
        REFERENCES dbo.[Catalog] (CatalogID)
        ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT CK_ORDER_ITEM_Quantity CHECK (Quantity > 0),
    CONSTRAINT CK_ORDER_ITEM_UnitPrice CHECK (UnitPrice >= 0),
    CONSTRAINT CK_ORDER_ITEM_ItemRef CHECK (
        (AlbumID IS NOT NULL AND CatalogID IS NULL) OR
        (AlbumID IS NULL AND CatalogID IS NOT NULL)
    )
);
GO

-- 3.5 PAYMENT
CREATE TABLE dbo.[PAYMENT] (
    PaymentID INT IDENTITY(1,1) NOT NULL,
    OrderID INT NOT NULL,
    PaymentDate DATETIME2 NOT NULL DEFAULT GETDATE(),
    Amount DECIMAL(10,2) NOT NULL,
    PaymentMethod NVARCHAR(50) NOT NULL,
    TransactionReference NVARCHAR(100) NOT NULL,
    PaymentStatus NVARCHAR(20) NOT NULL DEFAULT 'Completed',
    CONSTRAINT PK_PAYMENT PRIMARY KEY CLUSTERED (PaymentID),
    CONSTRAINT UQ_PAYMENT_OrderID UNIQUE (OrderID),
    CONSTRAINT UQ_PAYMENT_TransactionRef UNIQUE (TransactionReference),
    CONSTRAINT FK_PAYMENT_ORDERS FOREIGN KEY (OrderID)
        REFERENCES dbo.[ORDERS] (OrderID)
        ON DELETE NO ACTION ON UPDATE CASCADE,
    CONSTRAINT CK_PAYMENT_Amount CHECK (Amount >= 0),
    CONSTRAINT CK_PAYMENT_Status CHECK (PaymentStatus IN ('Pending', 'Completed', 'Failed', 'Refunded'))
);
GO


-- 4. PROMOTION & FAQ MODULE

-- 4.1 PROMOTION
CREATE TABLE dbo.[PROMOTION] (
    PromotionID INT IDENTITY(1,1) NOT NULL,
    PromotionName NVARCHAR(100) NOT NULL,
    Description NVARCHAR(MAX) NULL,
    DiscountType NVARCHAR(20) NOT NULL,
    DiscountValue DECIMAL(10,2) NOT NULL,
    StartDate DATETIME2 NOT NULL,
    EndDate DATETIME2 NOT NULL,
    PromotionStatus NVARCHAR(20) NOT NULL DEFAULT 'Active',
    CONSTRAINT PK_PROMOTION PRIMARY KEY CLUSTERED (PromotionID),
    CONSTRAINT CK_PROMOTION_DiscountType CHECK (DiscountType IN ('Percentage', 'FixedAmount')),
    CONSTRAINT CK_PROMOTION_DiscountValue CHECK (DiscountValue > 0),
    CONSTRAINT CK_PROMOTION_Dates CHECK (EndDate >= StartDate),
    CONSTRAINT CK_PROMOTION_Status CHECK (PromotionStatus IN ('Active', 'Expired', 'Scheduled', 'Cancelled'))
);
GO

-- 4.2 ALBUM_PROMOTION (Junction Table)
CREATE TABLE dbo.[ALBUM_PROMOTION] (
    AlbumID INT NOT NULL,
    PromotionID INT NOT NULL,
    CONSTRAINT PK_ALBUM_PROMOTION PRIMARY KEY CLUSTERED (AlbumID, PromotionID),
    CONSTRAINT FK_ALBUM_PROMOTION_ALBUM FOREIGN KEY (AlbumID)
        REFERENCES dbo.[ALBUM] (AlbumID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_ALBUM_PROMOTION_PROMOTION FOREIGN KEY (PromotionID)
        REFERENCES dbo.[PROMOTION] (PromotionID)
        ON DELETE CASCADE ON UPDATE CASCADE
);
GO

-- 4.3 FAQ
CREATE TABLE dbo.[FAQ] (
    FAQID INT IDENTITY(1,1) NOT NULL,
    Question NVARCHAR(500) NOT NULL,
    Answer NVARCHAR(MAX) NOT NULL,
    FAQStatus NVARCHAR(20) NOT NULL DEFAULT 'Published',
    CreatedDate DATETIME2 NOT NULL DEFAULT GETDATE(),
    UpdatedDate DATETIME2 NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_FAQ PRIMARY KEY CLUSTERED (FAQID),
    CONSTRAINT CK_FAQ_Status CHECK (FAQStatus IN ('Published', 'Draft', 'Archived'))
);
GO


-- 5. COMPLAINT & REVIEW MODULE


-- 5.1 COMPLAINT
CREATE TABLE dbo.[COMPLAINT] (
    ComplaintID INT IDENTITY(1,1) NOT NULL,
    ListenerID INT NOT NULL,
    Subject NVARCHAR(200) NOT NULL,
    Description NVARCHAR(MAX) NOT NULL,
    ComplaintDate DATETIME2 NOT NULL DEFAULT GETDATE(),
    Status NVARCHAR(20) NOT NULL DEFAULT 'Open',
    Response NVARCHAR(MAX) NULL,
    ResolvedDate DATETIME2 NULL,
    CONSTRAINT PK_COMPLAINT PRIMARY KEY CLUSTERED (ComplaintID),
    CONSTRAINT FK_COMPLAINT_LISTENER FOREIGN KEY (ListenerID)
        REFERENCES dbo.[LISTENER] (ListenerID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT CK_COMPLAINT_Status CHECK (Status IN ('Open', 'In Progress', 'Resolved', 'Closed'))
);
GO

-- 5.2 REVIEW
CREATE TABLE dbo.[REVIEW] (
    ReviewID INT IDENTITY(1,1) NOT NULL,
    ListenerID INT NOT NULL,
    AlbumID INT NOT NULL,
    Rating INT NOT NULL,
    Comment NVARCHAR(MAX) NULL,
    ReviewDate DATETIME2 NOT NULL DEFAULT GETDATE(),
    ReviewStatus NVARCHAR(20) NOT NULL DEFAULT 'Pending',
    CONSTRAINT PK_REVIEW PRIMARY KEY CLUSTERED (ReviewID),
    CONSTRAINT FK_REVIEW_LISTENER FOREIGN KEY (ListenerID)
        REFERENCES dbo.[LISTENER] (ListenerID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_REVIEW_ALBUM FOREIGN KEY (AlbumID)
        REFERENCES dbo.[ALBUM] (AlbumID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT CK_REVIEW_Rating CHECK (Rating BETWEEN 1 AND 5),
    CONSTRAINT CK_REVIEW_Status CHECK (ReviewStatus IN ('Pending', 'Approved', 'Rejected'))
);
GO


-- 6. DIGITAL LIBRARY & DOWNLOAD MODULE

-- 6.1 DIGITAL_LIBRARY
CREATE TABLE dbo.[DIGITAL_LIBRARY] (
    LibraryID INT IDENTITY(1,1) NOT NULL,
    ListenerID INT NOT NULL,
    CreatedDate DATETIME2 NOT NULL DEFAULT GETDATE(),
    LastUpdatedDate DATETIME2 NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_DIGITAL_LIBRARY PRIMARY KEY CLUSTERED (LibraryID),
    CONSTRAINT UQ_DIGITAL_LIBRARY_ListenerID UNIQUE (ListenerID),
    CONSTRAINT FK_DIGITAL_LIBRARY_LISTENER FOREIGN KEY (ListenerID)
        REFERENCES dbo.[LISTENER] (ListenerID)
        ON DELETE CASCADE ON UPDATE CASCADE
);
GO

-- 6.2 LIBRARY_ITEMS
CREATE TABLE dbo.[LIBRARY_ITEMS] (
    LibraryItemID INT IDENTITY(1,1) NOT NULL,
    LibraryID INT NOT NULL,
    AlbumID INT NOT NULL,
    CatalogID INT NULL,
    AddedDate DATETIME2 NOT NULL DEFAULT GETDATE(),
    PurchaseType NVARCHAR(50) NOT NULL DEFAULT 'Album',
    AccessStatus NVARCHAR(20) NOT NULL DEFAULT 'Active',
    CONSTRAINT PK_LIBRARY_ITEMS PRIMARY KEY CLUSTERED (LibraryItemID),
    CONSTRAINT UQ_LIBRARY_ITEMS_LibraryAlbum UNIQUE (LibraryID, AlbumID),
    CONSTRAINT FK_LIBRARY_ITEMS_DIGITAL_LIBRARY FOREIGN KEY (LibraryID)
        REFERENCES dbo.[DIGITAL_LIBRARY] (LibraryID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_LIBRARY_ITEMS_ALBUM FOREIGN KEY (AlbumID)
        REFERENCES dbo.[ALBUM] (AlbumID)
        ON DELETE NO ACTION ON UPDATE CASCADE,
    CONSTRAINT FK_LIBRARY_ITEMS_Catalog FOREIGN KEY (CatalogID)
        REFERENCES dbo.[Catalog] (CatalogID)
        ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT CK_LIBRARY_ITEMS_PurchaseType CHECK (PurchaseType IN ('Album', 'Catalog')),
    CONSTRAINT CK_LIBRARY_ITEMS_AccessStatus CHECK (AccessStatus IN ('Active', 'Revoked', 'Expired')),
    CONSTRAINT CK_LIBRARY_ITEMS_CatalogRef CHECK (
        (PurchaseType = 'Album' AND CatalogID IS NULL) OR
        (PurchaseType = 'Catalog' AND CatalogID IS NOT NULL)
    )
);
GO

-- 6.3 DOWNLOAD
CREATE TABLE dbo.[DOWNLOAD] (
    DownloadID INT IDENTITY(1,1) NOT NULL,
    LibraryItemID INT NOT NULL,
    DownloadDateTime DATETIME2 NOT NULL DEFAULT GETDATE(),
    FileFormat NVARCHAR(20) NOT NULL DEFAULT 'MP3',
    FileSize BIGINT NOT NULL,
    DownloadStatus NVARCHAR(20) NOT NULL DEFAULT 'Completed',
    CONSTRAINT PK_DOWNLOAD PRIMARY KEY CLUSTERED (DownloadID),
    CONSTRAINT FK_DOWNLOAD_LIBRARY_ITEMS FOREIGN KEY (LibraryItemID)
        REFERENCES dbo.[LIBRARY_ITEMS] (LibraryItemID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT CK_DOWNLOAD_FileSize CHECK (FileSize >= 0),
    CONSTRAINT CK_DOWNLOAD_Status CHECK (DownloadStatus IN ('Completed', 'Failed', 'Interrupted'))
);
GO

